server:
  port: 9001

staff:
  name: sunyang
  age: 26
  sex: 1
  address: hangzhou


#spring:
#  application:
#    name: springboot
#management:
#  endpoints:
#    web:
#      exposure:
#        include: /*
#  metrics:
#    tags:
#      application: ${spring.application.name}

