@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant 用户 as user
participant 线下门店 as webpos
participant 三方控额 as thirdParty
participant 交易服务 as core

user -> webpos : 出示二维码或身份证等等

activate webpos

webpos -> prepay : 校验
activate prepay

prepay -> hys : 调用好医生  "身份校验接口"
activate hys
return 返回结果
return 返回结果
webpos -> prepay : 是好医生用户（走好医生消费逻辑）
activate prepay

prepay -> hys : 调用好医生  "身份余额查询接口"
activate hys
return 返回客户号和余额

prepay -> account : 校验客户号是否存在普康系统（不存在则自动承保）
activate account
return 自动承保成功

prepay -> hys : 调用好医生  "门店查询接口"
activate hys
return 返回好医生门店code

prepay -> hys : 调用好医生  "预支付接口"
activate hys
return 成功(二维码消费需要轮询)

prepay -> prepay : 轮训调用好医生  "支付方案查询接口"

user -> hys : 用户输入密码
activate hys

hys -> hys : （校验密码成功）修改订单状态可以支付
return 密码验证成功

prepay -> prepay : 轮训检测到订单可以支付

return 告知门店客服订（需要自付金额）

webpos -> prepay : 门店客服确认支付（调用预支付进行校验）
activate prepay
prepay -> pay : 校验成功进行扣款
activate pay
pay -> hys : 普康扣款成功（调用好医生pay接口）
activate hys
return 好医生支付成功
return 消费成功
@enduml