@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant 用户 as user
participant app as app
participant 支付网关 as pay
participant 定时任务 as timing
participant 微信 as wx
participant 消费服务 as core
participant 中间服务 as custom


user -> app : 进入app选择商品
activate app

app -> pay : 选择完商品，点击下单
activate pay

pay -> core : 校验客户基本信息
activate core
return 返回结果

pay -> core : 调用支付接口
activate core

core -> custom : 校验山东国网人员状态
activate custom
return 返回结果

core -> custom : 交易成功（生成交易记录，账户扣款），\n判断有没有联合支付，(没有则调国网扣款接口)
activate custom

custom -> custom : 判断用户是否有补偿，\n有的话计算补偿后，\n再把金额推送国网
return 返回结果
return 返回扣款结果
return 返回扣款结果

app -> wx : 如果有联合支付，调用微信付款接口
activate wx

wx -> app : 扣款成功，回调app
app -> pay : 查询订单状态
activate pay
wx -> pay : 扣款成功，回调pay
activate pay
deactivate wx

user -> app : 点击查询订单状态
pay -> custom : 微信扣款成功调用中间服务插入数据
activate custom
custom -> custom : 判断是否是国网的，\n是的话走"9"逻辑
return 返回结果

pay -> pay : 微信支付成功，国网支付成功\n修改订单状态

timing -> core : 如果订单状态是5（冻结）\n则发起退款
activate core

core -> core : 是国网的不能退款\n（再额外加个校验\n如果订单状态是未支付\n也允许退款）
return 退款成功

@enduml